server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service-users
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: employee-service-employees
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthenticationFilter

        - id: employee-service-departments
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/departments/**
          filters:
            - AuthenticationFilter

        - id: employee-service-positions
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/positions/**
          filters:
            - AuthenticationFilter

        - id: employee-service-attendance
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/attendance/**
          filters:
            - AuthenticationFilter

        - id: employee-service-leaves
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/leaves/**
          filters:
            - AuthenticationFilter

        - id: employee-service-salaries
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/salaries/**
          filters:
            - AuthenticationFilter

        - id: employee-service-dashboard
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/dashboard/**
          filters:
            - AuthenticationFilter

        - id: document-service-docs
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/api/v1/documents/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false
            maxAge: 3600

jwt:
  secret: ${JWT_SECRET:8d414e13c9cb1ccc8b88c38d4f3ec22f8318473a980d9134bda2d8d783d73bc7}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}