server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config-repo/

        git:
          uri: https://github.com/Alokafernando/smarthr-configurations.git
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 10
          search-paths:
            - platform
            - servers
            - '{application}'

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info